#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# Everything lands here, not in .env — .env.local is what this project reads
# for local development and it is gitignored.
ENV_FILE=".env.local"

SLACK_APP_NAME="Luma Shots"

# Printed twice: once with scopes only (before a public URL exists), once with
# the slash command and interactivity pointing at the deployed service.
print_manifest() {
  local url="${1:-}"
  cat <<MANIFEST
display_information:
  name: ${SLACK_APP_NAME}
  description: Turns catalog shot ideas into styled product photos
  background_color: "#2b2b2b"
features:
  bot_user:
    display_name: ${SLACK_APP_NAME}
    always_online: true
MANIFEST
  if [[ -n "$url" ]]; then
    # One command per verb, so Slack's typeahead can suggest and filter them.
    # `/luma <verb>` still works — the handler takes the verb from the command
    # name when there is one and from the text otherwise.
    cat <<MANIFEST
  slash_commands:
    - command: /luma
      url: ${url}/slack/commands
      description: Styled product shots — run without arguments for the full list
      usage_hint: upload | status | signin | generate | system-prompt | access | help
      should_escape: false
    - command: /luma-upload
      url: ${url}/slack/commands
      description: Read a catalog CSV and price the batch before anything is spent
      usage_hint: (opens a window — attach the CSV there)
      should_escape: false
    - command: /luma-status
      url: ${url}/slack/commands
      description: Where the latest batch stands and what still needs deciding
      usage_hint: (no arguments)
      should_escape: false
    - command: /luma-signin
      url: ${url}/slack/commands
      description: Get a private link that lets you approve, discard and confirm
      usage_hint: (no arguments — the link lasts a day)
      should_escape: false
    - command: /luma-generate
      url: ${url}/slack/commands
      description: Try an idea on one photo of your own; the result comes back in your DMs
      usage_hint: (opens a window — attach a photo and write the prompt)
      should_escape: false
    - command: /luma-system-prompt
      url: ${url}/slack/commands
      description: See and change the wording that turns a shot idea into three prompts
      usage_hint: (opens a window — clear the box to revert)
      should_escape: false
    - command: /luma-access
      url: ${url}/slack/commands
      description: See and change who can approve, discard and confirm
      usage_hint: (approver only — opens a window)
      should_escape: false
    - command: /luma-help
      url: ${url}/slack/commands
      description: List every command and what it does
      usage_hint: (no arguments)
      should_escape: false
MANIFEST
  fi
  cat <<MANIFEST
oauth_config:
  scopes:
    bot:
      - commands
      - chat:write
      - files:write
      - files:read
      - im:write
      - pins:write
settings:
MANIFEST
  if [[ -n "$url" ]]; then
    cat <<MANIFEST
  interactivity:
    is_enabled: true
    request_url: ${url}/slack/interactions
MANIFEST
  fi
  cat <<MANIFEST
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
MANIFEST
}

banner "Styled Shot Pipeline — stack setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Railway: project and Postgres"
say "The database first, because nothing else depends on it."
open_url "https://railway.com/new"
step "Sign in, then create a new empty project."
step "Inside it: 'Create' → 'Database' → 'Add PostgreSQL'."
step "Click the Postgres service → 'Variables' tab."
step "Copy DATABASE_PUBLIC_URL (NOT DATABASE_URL)."
note "DATABASE_URL is Railway-internal and only resolves between services in"
note "the project. The public one is what your laptop can reach, and it is"
note "what this file is for. The deployed service can be switched to the"
note "internal one later for speed."
ask_secret DATABASE_URL "Paste DATABASE_PUBLIC_URL:"
write_env DATABASE_URL "$DATABASE_URL"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Slack: a workspace of your own"
say "A fresh workspace, so you can restrict a channel and test notification"
say "behaviour without affecting anyone. Its invite link is also how a"
say "reviewer gets in."
open_url "https://slack.com/get-started#/createnew"
step "Create the workspace. Any name; skip the invite-teammates step."
pause "Press Enter once the workspace is open."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Slack: create the app from a manifest"
say "Pasting a manifest sets every scope at once instead of ticking boxes."
say "No slash command yet — that needs a public URL, which comes at stage 6."
printf '\n'
print_manifest ""
printf '\n'
step "Copy the YAML above."
open_url "https://api.slack.com/apps?new_app=1"
step "'Create New App' → 'From a manifest' → pick your new workspace."
step "Delete the placeholder, paste the YAML, Next → Create."
step "On the app page: 'Install App' (left sidebar) → 'Install to Workspace' → Allow."
pause "Press Enter once the app is installed."

step "'OAuth & Permissions' → copy the Bot User OAuth Token (starts xoxb-)."
ask_secret SLACK_BOT_TOKEN "Paste the bot token:"
write_env SLACK_BOT_TOKEN "$SLACK_BOT_TOKEN"

step "'Basic Information' → App Credentials → Signing Secret → Show → copy."
ask_secret SLACK_SIGNING_SECRET "Paste the signing secret:"
write_env SLACK_SIGNING_SECRET "$SLACK_SIGNING_SECRET"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Slack: the review channel"
say "One dedicated channel. Ellie scrolls it; the images live here."
step "In Slack, create a public channel — #shot-review is a good name."
step "In the channel, type:  /invite @${SLACK_APP_NAME}"
printf '\n'
say "Now restrict who can post at the top level, keeping threads open:"
step "Channel name → 'Settings' tab → 'Manage posting permissions'."
step "Restrict posting to yourself and the app."
warn "Leave 'Also restrict thread replies' UNCHECKED."
note "Restricted top-level posting keeps the review stream scannable; open"
note "threads are where the team's opinions land. Losing threads would trade"
note "the discussion for tidiness, which is the wrong way round."
printf '\n'
note "If the app cannot post once restricted, that is a real finding — it is"
note "exactly what ticket 02 exists to check, and the design has a fallback."
printf '\n'
step "Channel name → 'About' tab → scroll to the bottom → copy the Channel ID."
ask SLACK_REVIEW_CHANNEL_ID "Paste the channel ID (starts C):"
write_env SLACK_REVIEW_CHANNEL_ID "$SLACK_REVIEW_CHANNEL_ID"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Slack: who is allowed to approve"
say "In v1 exactly one person can approve or discard. Everyone else can still"
say "discuss in threads — the decision simply stays where it already sits."
step "Click your avatar (top right) → 'Profile'."
step "In the profile panel: 'More' (⋮) → 'Copy member ID'."
ask SLACK_APPROVER_USER_ID "Paste the member ID (starts U):"
write_env SLACK_APPROVER_USER_ID "$SLACK_APPROVER_USER_ID"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Railway: deploy the service"
say "Railway builds from the Dockerfile in this repo, so the branch has to be"
say "pushed first."
printf '\n'
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
if [[ -n "$CURRENT_BRANCH" ]]; then
  say "Current branch: ${BOLD}${CURRENT_BRANCH}${RESET}"
  if confirm "Push it to origin now?"; then
    git push -u origin "$CURRENT_BRANCH" || warn "push failed — push it yourself, then continue"
  else
    SKIPPED+=("git push origin $CURRENT_BRANCH")
  fi
fi
printf '\n'
open_url "https://railway.com/dashboard"
step "Open the SAME project that holds your Postgres."
step "'Create' → 'GitHub Repo' → authorise if asked → pick luma-take-home."
step "Choose the branch you just pushed. Railway detects the Dockerfile itself."
printf '\n'
step "On the new service: 'Variables' → 'Raw Editor'."
step "Paste the entire contents of ${ENV_FILE}, then Save."
note "Railway will redeploy. Without these five values the service exits at"
note "boot on purpose, naming every one that is missing at once."
printf '\n'
step "'Settings' → 'Networking' → 'Generate Domain' → accept the port (3000)."
ask PUBLIC_URL "Paste the generated URL (https://…):"
PUBLIC_URL="${PUBLIC_URL%/}"
write_env PUBLIC_URL "$PUBLIC_URL"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Slack: point the app at the deployed service"
say "Now that a public URL exists, the manifest can carry the slash command"
say "and the interactivity endpoint the buttons will use."
printf '\n'
print_manifest "$PUBLIC_URL"
printf '\n'
step "Copy the YAML above."
open_url "https://api.slack.com/apps"
step "Open your app → 'App Manifest' (left sidebar, under Features)."
step "Select everything in the editor, paste over it, then 'Save Changes'."
step "If Slack asks you to reinstall, do it."
pause "Press Enter once the manifest is saved."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Check it actually works"
say "Two checks: the machine one, then the human one."
printf '\n'
if command -v curl >/dev/null 2>&1; then
  say "Asking ${PUBLIC_URL}/healthz …"
  HEALTH=$(curl -s -m 15 "${PUBLIC_URL}/healthz" || true)
  if [[ "$HEALTH" == *'"ok"'* ]]; then
    printf '  %s✓%s service is up: %s\n' "$GREEN" "$RESET" "$HEALTH"
  else
    warn "no healthy response yet (got: ${HEALTH:-nothing})"
    note "Railway may still be building. Check the service's Deploy logs —"
    note "a missing variable is reported by name at startup."
    SKIPPED+=("confirm ${PUBLIC_URL}/healthz returns {\"status\":\"ok\"}")
  fi
else
  SKIPPED+=("check ${PUBLIC_URL}/healthz returns ok")
fi
printf '\n'
step "In Slack, in your review channel, type:  /luma ping"
say "You should get: 'pong — deployed and listening.'"
step "Then try:  /luma status"
say "You should get: 'No batches yet. Upload a catalog to get started.'"
printf '\n'
if ! confirm "Did /luma ping answer?"; then
  SKIPPED+=("/luma ping did not answer — check Railway logs and the slash command URL")
  warn "Most common causes: the manifest URL has a typo, or the deploy is"
  warn "still building. The URL must end in /slack/commands."
fi

finish
